### ISSUE TITLE
BUG🐞: 장바구니에 이미 있던 상품을 또 추가할 때 수량이 10개보다 넘어가는 문제 발생

### ISSUE THREAD

**Issue by uuuuujin** [vegeten/vegeten-shop#22]
## 현재 로직
- 장바구니에 이미 존재하는 상품을 또 추가하게되면 `원래 담겨있던 수량 + 추가하려는 수량` 이렇게 플러스가 됨

## 문제점
- 상품 구매시 수량 최대를 10개로 제한해놔서 장바구니에도 최대 10개로 해놨는데 이를 초과해버리는 문제 발생

**Comment by JiyoonZ** [comment]
상품 상세에서 장바구니 페이지로 넘어갈때 10개로 제한이 되지만
1. 두번째로 똑같은 상품을 또 장바구니에 담을때 10개가 넘어간다.
<hr>
갯수 제한을 없애도록 할까요? <br>
대신 구매시 잘못해서 한명이 1000개를 구매하는 (만약에 수량이 100개밖에 없는데) 상황이 있는 이슈도 생기니까<br>
상품 등록시 제한 수량을 추가하는 방향도 생각해야 할것 같네요🤔

**Comment by uuuuujin** [comment]
아 거기까지 생각을 못했었네요..

근데 만약 상품별로 수량이 다르다면 구매할 때 가능한 최대 수량을 어떻게 처리해야 할까요..?

**Comment by task11** [comment]
좋아요👍🏽 지금 상태에서는 갯수 제한을 없애고,

input에 직접 넣을 경우를 대비해서 maxLength값을 (ex maxLength=2) 조절해서 99개 이상 구매할 수 없게하는 것도 방법인 것 같아요

~사실 욕심은 상품 수량 정보를 상품 정보 스키마에 추가하거나 배송or물류 관련 스키마를 만들어서 관리하면 좋을 것 같긴해요 😏~
